In [9]:
import pandas as pd
import glob

In [29]:
df_addr = pd.read_csv('C:/Users/tjoeun/Desktop/송수린/workspace/weather_project/data/관측소주소.csv', encoding='cp949')

In [33]:
import os
os.chdir('C:/Users/tjoeun/Desktop/송수린/workspace/weather_project/data/예측용')
file_names=os.listdir()

In [53]:
file_names

['강화 관측소.xls',
 '고산 관측소(2022.07).xls',
 '고산 관측소(2022.10).xls',
 '금산 관측소(2022.07).xls',
 '금산 관측소(2022.10).xls',
 '대구 관측소.xls',
 '목포 관측소.xls',
 '서울 관측소.xls',
 '순창군 관측소.xls',
 '울릉도 관측소.xls',
 '의령군 관측소(2022.07).xls',
 '의령군 관측소(2022.10).xls',
 '의성 관측소(2022.07).xls',
 '의성 관측소(2022.10).xls',
 '정선군 관측소.xls',
 '제주 관측소.xls',
 '청주 관측소(2022.07).xls',
 '청주 관측소(2022.10).xls',
 '충주 관측소.xls',
 '통영 관측소(2022.07).xls',
 '통영 관측소(2022.10).xls',
 '포항 관측소.xls']

In [60]:
columns = ['지점명', '일시', 'PM10', 'PM2.5', 'O3', 'NO2', 'CO', 'SO2']
excel = pd.DataFrame(columns=columns)
for observ in file_names:
    try:
        path = 'C:/Users/tjoeun/Desktop/송수린/workspace/weather_project/data/예측용/'
        files = glob.glob(path + f'{observ}')
        df = pd.read_excel(files[0], header=5)
        df = df[df.columns[0::2]]
        df.columns = ['일시', 'PM10', 'PM2.5', 'O3', 'NO2', 'CO', 'SO2']
        df['일시'] = df['일시'].apply(lambda x: (x.replace(':', ' ') + ':00'))
        df['지점명'] = observ.split(' ')[0]
        excel = pd.concat([excel, df], axis=0)
        
        excel.sort_values('일시', inplace=True)
        excel.to_csv(path + '예측용관측소.csv', index=False)

    except Exception as ex:
        print('error' + str(ex))

In [61]:
df=pd.read_csv('C:/Users/tjoeun/Desktop/송수린/workspace/weather_project/data/예측용/예측용관측소.csv')

In [63]:
df

       지점명                일시  PM10  PM2.5     O3    NO2   CO    SO2
0       고산  2022-07-01 01:00   NaN    5.0    NaN  0.002  NaN  0.000
1       의성  2022-07-01 01:00  17.0    5.0  0.010  0.006  0.2  0.002
2       금산  2022-07-01 01:00  12.0    6.0  0.012  0.006  0.2  0.003
3       통영  2022-07-01 01:00  14.0    3.0  0.011  0.011  0.4  0.002
4      의령군  2022-07-01 01:00  11.0    8.0  0.011  0.004  0.2  0.002
...    ...               ...   ...    ...    ...    ...  ...    ...
15643   서울  2023-02-28 24:00  25.0   21.0  0.026  0.035  0.5  0.003
15644  울릉도  2023-02-28 24:00  26.0    9.0  0.050  0.009  0.3  0.002
15645   포항  2023-02-28 24:00  25.0   15.0  0.044  0.015  0.5  0.002
15646  순창군  2023-02-28 24:00  28.0   24.0  0.026  0.010  0.1  0.002
15647   대구  2023-02-28 24:00  40.0   24.0  0.012  0.051  0.6  0.004

[15648 rows x 8 columns]